print('\n\n --- \n\n')
print '                 ````         '
print '                /NMMM.        '
print '              `hMMMMM.        '
print '             /NMMyMMM.        '
print '           `yMMd--MMM.        '
print '          :NMMo  -MMM.        '
print '        `sMMd-   -MMM.        '
print '       -mMMo     -MMM.        '
print '      sMMm-      -MMM.        '
print '    .mMMm++++++++sMMM+++/     '
print '    /MMMMMMMMMMMMMMMMMMMN     '
print '    `............sMMM:...     '
print '                 oMMM.        '
print '                 oMMM.        '
print '                 oMMM.        '
print '                 `---         '
print('\n\n --- \n\n')
