print('\n\n --- \n\n')
print '           .--:-.`            '
print '       .odNMMMMMMMms.         '
print '      oMMMMMNmmNMMMMMs        '
print '     /MMMMN/    :NMMMMo       '
print '     shdmm+      oMMMMh       '
print '                `dMMMMo       '
print '               :dMMMMh        '
print '             :hMMMMMs         '
print '           /dMMMMMy.          '
print '         /mMMMMNy.            '
print '       :dMMMMNo`              '
print '      sMMMMMm/---------       '
print '     yMMMMMMMMMMMMMMMMh       '
print '    :MMMMMMMMMMMMMMMMMh       '
print '    ```````````````````       '
print('\n\n --- \n\n')
