print('\n\n --- \n\n')
print '             -:::::::.     '
print '            /dddddhhhh     '
print '           :hdddddhhhd`    '
print '       `./sdhdddhhhhhd`    '
print '  `/+osyhhhhhhhhhhhhhh`    '
print '  /dhhdhhhvhhhhhhhhhhh`    '
print '  :dhhhdddhhhhhhhhhhhh`    '
print '            .dhhhhhhhh`    '
print '            .dddhhhhhh     '
print '            .ddddddddh`    '
print '            .ddddddddh`    '
print '            .ddddddddh`    '
print '            .ddddddddh`    '
print '            .mdddddddh     '
print '            .mddmddddd     '
print '            .mmmmmmmmh     '
print '            `mdddddmmh     '
print '            `mmmmmmmmh     '
print '             ////////:     '
print('\n\n --- \n\n')
